HTML_SELECTOR = {'BOOTCAMPS': sorted(['Cyber', 'Data', 'Marketing', 'Product', 'Ux/Ui', 'Web', 'Web3', 'Game', 'Mobile']),

                 'COUNTRIES': sorted(['Brazil', 'Canada', 'Cyprus', 'Denmark', 'England', 'France', 'Germany',
                                      'Greece', 'Italy', 'Luxembourg', 'Malaysia', 'Malta', 'Mexico', 'Netherland',
                                      'Portugal', 'Spain', 'Sweden', 'USA', 'Wales', 'Ireland', 'Scotland',
                                      'Poland', 'Switzerland', 'Morocco', 'Tunisia', 'Finland', 'Turkey',
                                      'Austria', 'Belgium', 'Liechtenstein', 'Iceland', 'Norway',
                                      'Estonia', 'Hungary', 'Czech', 'Slovakia', 'Romania', 'Bosnia',
                                      'Indonesia', 'Australia', 'Russia', 'Ukraine', 'Croatia', 'Israel',
                                      'Lebanon', 'Argentina', 'Philippines', 'Korea', 'New_Zealand',
                                      'Thailand', 'Japan', 'Vietnam', 'China', 'India', 'South_Africa',
                                      'Egypt',
                                      ]),

                 'DATE': ['Last_Week', 'Last_Month', 'Last_Trimester'],

                 'EXPERIENCE': ['All', 'Internship', 'Entry_Level', 'Mid_Level', 'Senior_Level'],

                 'JOB_TYPE': ['All', 'Presential', 'Remote', 'Hybrid'],

                 'METRIC': ['Time_series_line', 'Time_series_bar', 'Comparative', 'Keywords', 'Keyword_race',
                            'Treemap', 'Sunburst', 'Enterprises', 'Enterprises_30', 'Skills', 'Skill_race'],

                 'STATE/PROVINCE': {

                     'USA': ['All'] + sorted(
                         ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut',
                          'Delaware', 'District_of_Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois',
                          'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts',
                          'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
                          'New_Hampshire', 'New_Jersey', 'New_Mexico', 'New_York', 'North_Carolina', 'North_Dakota',
                          'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South_Carolina',
                          'South_Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
                          'West_Virginia', 'Wisconsin', 'Wyoming']),

                     'Brazil': ['All'] + sorted(['Acre', 'Alagoas', 'Amapá', 'Amazonas', 'Bahia', 'Ceará',
                                                 'Distrito_Federal', 'Federal_District', 'Espírito_Santo', 'Goiás',
                                                 'Maranhão',
                                                 'Mato_Grosso', 'Mato_Grosso_do_Sul', 'Minas_Gerais', 'Pará',
                                                 'Paraíba', 'Paraná', 'Pernambuco', 'Piauí', 'Rio_de_Janeiro',
                                                 'Rio_Grande_do_Norte', 'Rio_Grande_do_Sul', 'Rondônia', 'Roraima',
                                                 'Santa_Catarina', 'São Paulo', 'Sergipe', 'Tocantins']),

                     'England': ['All'] + sorted(['Barking', 'Dagenham', 'Bath', 'North_East_Somerset', 'Bedfordshire',
                                                  'Berkshire', 'Bexley', 'Blackburn_with_Darwen', 'Bournemouth',
                                                  'Brent', 'Brighton',
                                                  'Hove', 'Bristol', 'Bromley', 'Buckinghamshire', 'Cambridgeshire',
                                                  'Camden',
                                                  'Cheshire', 'Cornwall', 'Croydon', 'Cumbria', 'Darlington',
                                                  'Derbyshire', 'Derby',
                                                  'Devon', 'Dorset', 'Durham', 'Ealing', 'East_Riding_of_Yorkshire',
                                                  'East_Sussex',
                                                  'Enfield', 'Essex', 'Gloucestershire', 'Greenwich', 'Hackney',
                                                  'Halton', 'Hammersmith',
                                                  'Fulham', 'Hampshire', 'Haringey', 'Harrow', 'Hartlepool', 'Havering',
                                                  'Herefordshire',
                                                  'Hertfordshire', 'Hillingdon', 'Hounslow', 'Isle_of_Wight',
                                                  'Islington', 'Kensington',
                                                  'Chelsea', 'Kent', 'Kingston_upon_Hull', 'Kingston_upon_Thames',
                                                  'Lambeth',
                                                  'Lancashire', 'Leicestershire', 'Leicester', 'Lewisham',
                                                  'Lincolnshire', 'London',
                                                  'Luton', 'Manchester', 'Medway', 'Merseyside', 'Merton',
                                                  'Middlesbrough',
                                                  'Milton_Keynes', 'Newham', 'Norfolk', 'North_East_Lincolnshire',
                                                  'North_Lincolnshire',
                                                  'North_Somerset', 'North_Yorkshire', 'Northamptonshire',
                                                  'Northumberl',
                                                  'Nottinghamshire', 'Nottingham', 'Oxfordshire', 'Peterborough',
                                                  'Plymouth', 'Poole',
                                                  'Portsmouth', 'Redbridge', 'Redcar', 'Clevel', 'Richmond_upon_Thames',
                                                  'Rutl',
                                                  'Shropshire', 'Somerset', 'South_Gloucestershire', 'South_Yorkshire',
                                                  'Southampton',
                                                  'Southend-on-Sea', 'Southwark', 'Staffordshire', 'Stockton-on-Tees',
                                                  'Stoke-on-Trent',
                                                  'Suffolk', 'Surrey', 'Sutton', 'Swindon', 'Telford', 'Wrekin',
                                                  'Thurrock', 'Torbay',
                                                  'Tower_Hamlets', 'Tyne', 'Wear', 'Waltham_Forest', 'sworth',
                                                  'Warrington',
                                                  'Warwickshire', 'West_Midl', 'West_Sussex', 'West_Yorkshire',
                                                  'Westminster',
                                                  'Wiltshire', 'Worcestershire', 'York', 'Antrim', 'Ards', 'Armagh',
                                                  'Ballymena',
                                                  'Ballymoney', 'Banbridge', 'Belfast', 'Carrickfergus', 'Castlereagh',
                                                  'Coleraine',
                                                  'Cookstown', 'Craigavon', 'Derry', 'Down', 'Dungannon', 'Fermanagh',
                                                  'Larne',
                                                  'Limavady', 'Lisburn', 'Magherafelt', 'Moyle', 'Newry', 'Mourne',
                                                  'Newtownabbey',
                                                  'North_Down', 'Omagh', 'Strabane', 'Aberdeenshire', 'Aberdeen',
                                                  'Angus', 'Argyll',
                                                  'Bute', 'Clackmannanshire', 'Dumfries', 'Galloway', 'Dundee',
                                                  'East_Ayrshire',
                                                  'East_Dunbartonshire', 'East_Lothian', 'East_Renfrewshire',
                                                  'Edinburgh', 'Eilean_Siar',
                                                  'Falkirk', 'Fife', 'Glasgow', 'Highland', 'Inverclyde', 'Midlothian',
                                                  'Moray',
                                                  'North_Ayshire', 'North_Lanarkshire', 'Orkney_Isl', 'Perthshire',
                                                  'Kinross',
                                                  'Renfrewshire', 'Scottish_Borders', 'Shetl', 'South_Ayrshire',
                                                  'South_Lanarkshire',
                                                  'Stirling', 'West_Dunbartonshire', 'West_Lothian', 'Anglesey',
                                                  'Blaenau_Gwent',
                                                  'Bridgend', 'Caerphilly', 'Cardiff', 'Carmarthenshire', 'Ceredigion',
                                                  'Conwy',
                                                  'Denbighshire', 'Flintshire', 'Gwynedd', 'Merthyr_Tydfil',
                                                  'Monmouthshire',
                                                  'Neath_Port_Talbot', 'Newport', 'Pembrokeshire', 'Powys',
                                                  'Rhondda,_Cynon,_Taff',
                                                  'Swansea', 'Torfaen', 'Vale_of_Glamorgan', 'Wrexham']),

                     'France': ['All'] + sorted(['Alsace', 'Aquitaine', 'Auvergne', 'Brittany', 'Burgundy', 'Centre',
                                                 'Champagne-Ardenne', 'Corsica', 'Franche-Comté', 'Ile-de-France',
                                                 'Languedoc-Roussilion', 'Limousin', 'Lorraine', 'Normandy',
                                                 'Midi-Pyrenées', 'Calais',
                                                 'Loire', 'Picardy', 'Poitou-Charentes', 'Provence-Alpes-Cote',
                                                 'Rhone-Alpes']),

                     'Germany': ['All'] + sorted(
                         ['Baden-Württemberg', 'Bavaria', 'Berlin', 'Brandenburg', 'Bremen', 'Hamburg',
                          'Hesse', 'Lower_Saxony', 'Mecklenburg-Vorpommern', 'North_Rhine-Westphalia',
                          'Rhineland-Palatinate', 'Saarland', 'Saxony', 'Saxony-Anhalt', 'Schleswig-Holstein',
                          'Thuringia']),

                     'Mexico': ['All'] + sorted(['Aguascalientes', 'Baja_California', 'Baja_California_Sur', 'Campeche',
                                                 'Chiapas', 'Chihuahua', 'Coahuila', 'Colima', 'Durango', 'Guanajuato',
                                                 'Guerrero',
                                                 'Hidalgo', 'Jalisco', 'México', 'Mexico_City', 'Michoacán', 'Morelos',
                                                 'Nayarit',
                                                 'Nuevo_León', 'Oaxaca', 'Puebla', 'Querétaro', 'Quintana_Roo',
                                                 'San_Luis_Potosí',
                                                 'Sinaloa', 'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala', 'Veracruz',
                                                 'Yucatán',
                                                 'Zacatecas']),

                     'Netherland': ['All'] + sorted(['Groningen', 'Friesland', 'Gelderland', 'Utrecht', 'South_Holland',
                                                     'Zeeland', 'North_Brabant', 'Limburg', 'North_Holland',
                                                     'Flevoland', 'Drenthe',
                                                     'Overijssel']),

                     'Portugal': ['All'] + sorted(['Aveiro', 'Beja', 'Braga', 'Bragança', 'Castelo_Branco', 'Coimbra',
                                                   'Évora', 'Faro', 'Guarda', 'Leiria', 'Lisbon', 'Portalegre',
                                                   'Porto', 'Santarém', 'Setúbal', 'Viana_do_Castelo', 'Vila_Real',
                                                   'Viseu']),

                     'Spain': ['All'] + sorted(
                         ['Coruña', 'Álava', 'Albacete', 'Alicante', 'Almería', 'Asturias', 'Ávila',
                          'Badajoz', 'Balear', 'Barcelona', 'Vizcaya', 'Burgos', 'Cáceres', 'Cádiz', 'Cantabria',
                          'Castellón', 'Ciudad_Real', 'Córdoba', 'Cuenca', 'Guipúzcoa', 'Girona', 'Granada',
                          'Guadalajara', 'Huelva', 'Huesca', 'Jaén', 'La_Rioja', 'Las_Palmas', 'León', 'Lleida',
                          'Lugo', 'Madrid', 'Málaga', 'Murcia', 'Navarra', 'Ourense', 'Palencia', 'Pontevedra',
                          'Salamanca', 'Santa_Cruz_de_Tenerife', 'Segovia', 'Sevill', 'Soria', 'Tarragona',
                          'Teruel', 'Toledo', 'Valencia', 'Valladolid', 'Zamora', 'Zaragoza']),

                     'Canada': ['All'] + sorted(['Quebec', 'Newfoundland_and_Labrador', 'British_Columbia',
                                                 'Nunavut', 'Northwest_Territories', 'New_Brunswick', 'Nova_Scotia',
                                                 'Saskatchewan', 'Alberta', 'Prince_Edward_Island',
                                                 'Yukon_Territory', 'Manitoba', 'Ontario']),

                     'Cyprus': ['All'] + sorted(['British Overseas', 'Famagusta', 'Kerynia', 'Larnaca', 'Limassol',
                                                 'Nicosia', 'Paphos']),

                     'Denmark': ['All'] + sorted(['Brøndby', 'Copenhagen', 'København',
                                                  'Fredensborg', 'Fredericia', 'Frederikshavn', 'Frederikssund',
                                                  'Lejre', 'Jammerbugt', 'Kalundborg', 'Skive', 'Slagelse', 'Solrød',
                                                  'Furesø', 'Gentofte', 'Høje-Taastrup', 'Holbæk', 'Holstebro',
                                                  'Horsens', 'Hørsholm', 'Ringsted', 'Halsnæs', 'Hedensted',
                                                  'Helsingør', 'Langeland', 'Assens', 'Roskilde', 'Rudersdal',
                                                  'Samsø', 'Silkeborg', 'Skanderborg', 'Greve', 'Lemvig', 'Lolland',
                                                  'Lyngby-Taarbæk', 'Mariagerfjord', 'Middelfart', 'Morsø',
                                                  'Aabenraa', 'Aalborg', 'Aarhus', 'Ærø', 'Næstved', 'Norddjurs',
                                                  'Nordfyns', 'Nyborg', 'Odder', 'Odense', 'Odsherred',
                                                  'Ringkøbing-Skjern', 'Faaborg-Midtfyn', 'Fanø', 'Albertslund',
                                                  'Allerød', 'Ballerup', 'Billund', 'Bornholms', 'Favrskov', 'Faxe',
                                                  'Randers', 'Rebild', 'Brønderslev',
                                                  'Dragør', 'Egedal', 'Esbjerg', 'Frederiksberg', 'Læsø', 'Glostrup',
                                                  'Gribskov', 'Guldborgsund', 'Haderslev', 'Hjørring', 'Gladsaxe',
                                                  'Kerteminde', 'Køge', 'Kolding', 'Herlev', 'Herning', 'Hillerød',
                                                  'Hvidovre', 'Ikast-Brande', 'Ishøj', 'Rødovre', 'Sønderborg',
                                                  'Sorø', 'Stevns', 'Struer', 'Svendborg', 'Syddjurs', 'Tårnby',
                                                  'Thisted', 'Tønder', 'Vallensbæk', 'Varde', 'Vejen', 'Vejle',
                                                  'Vesthimmerlands', 'Viborg', 'Vordingborg']),

                     'Greece': ['All'] + sorted(['Athens', 'Thessaloniki', 'Eastern_Macedonia_and_Thrace',
                                                 'Central_Macedonia', 'Thessaly', 'Northern_Aegean', 'Southern_Aegean',
                                                 'Central_Greece', 'Western_Greece', 'Peloponnese', 'Attiki',
                                                 'West_Macedonia',
                                                 'Epirus', 'Ionian', 'Crete']),

                     'Italy': ['All'] + sorted(['Abruzzi', 'Basilicata', 'Calabria', 'Campania', 'Emilia-Romagna',
                                                'Friuli-Venezia', 'Latium', 'Liguria', 'Lombard', 'March', 'Molise',
                                                'Piedmont',
                                                'Apulia', 'Sardinia', 'Sicil', 'Tuscany', 'Trentino-Alto_Adige',
                                                'Umbria',
                                                "Valle_d'Aosta", 'Veneto']),

                     'Malta': ['All'] + sorted(
                         ['Birkirkara', 'Luqa', 'Marsa', 'Mosta', 'Msida', 'Naxxar', 'Sliema', "Ta'_Xbiex",
                          'Valletta']),

                     'Sweden': ['All'] + sorted(['Stockholm', 'Västmanland', 'Värmland', 'Örebro', 'Jämtland',
                                                 'Blekinge', 'Uppsala', 'Södermanland', 'Östergötland', 'Gotland',
                                                 'Jönköping', 'Kronoberg', 'Västernorrland', 'Kalmar', 'Skåne',
                                                 'Halland', 'Gävleborg', 'Västra_Götaland', 'Dalarna',
                                                 'Västerbotten', 'Norrbotten']),

                     'Malaysia': ['All'] + sorted(['Johor', 'Kedah', 'Kelantan', 'Kuala_Lumpur', 'Labuan', 'Melaka',
                                                   'Negeri_Sembilan', 'Pahang', 'Perak', 'Perlis', 'Pulau_Pinang',
                                                   'Putrajaya', 'Sabah', 'Sarawak', 'Selangor', 'Trengganu']),

                     'Luxembourg': ['All'] + sorted(['Echternach', 'Grevenmacher', 'Remich', 'Mersch', 'Capellen',
                                                     'Luxembourg', 'Redange', 'Diekirch', 'Esch-sur-Alzette',
                                                     'Clervaux', 'Wiltz', 'Vianden']),

                     'Wales': ['All'] + sorted(['Isle_of_Anglesey', 'Gwynedd', 'Conwy', 'Denbighshire',
                                                'Flintshire', 'Wrexham', 'Ceredigion', 'Pembrokeshire',
                                                'Carmarthenshire', 'Swansea', 'Neath_Port_Talbot', 'Bridgend',
                                                'Vale_of_Glamorgan', 'Cardiff', 'Rhondda_Cynon_Taf', 'Caerphilly',
                                                'Blaenau Gwent', 'Torfaen', 'Monmouthshire', 'Newport', 'Powys',
                                                'Merthyr Tydfil']),

                     'Ireland': ['All'] + sorted(['Carlow', 'Cavan', 'Clare', 'Cork', 'Donegal', 'Dublin',
                                                  'Dún Laoghaire-Rathdown', 'Fingal', 'Galway', 'Kerry', 'Kildare',
                                                  'Kilkenny', 'Laois', 'Leitrim', 'Limerick', 'Longford', 'Louth',
                                                  'Mayo', 'Meath', 'Monaghan', 'Offaly', 'Roscommon', 'Sligo',
                                                  'Tipperary', 'Waterford', 'Westmeath', 'Wexford', 'Wicklow']),

                     'Scotland': ['All'] + sorted(['Clackmannanshire', 'Dumfries_and_Galloway', 'East_Ayrshire',
                                                   'East_Lothian', 'East_Renfrewshire', 'Eilean_Siar', 'Falkirk',
                                                   'Fife', 'Highland', 'Inverclyde', 'Midlothian', 'Moray',
                                                   'North_Ayrshire', 'Orkney_Islands', 'Perth_and_Kinross',
                                                   'Scottish_Borders', 'Shetland_Islands', 'South_Ayrshire',
                                                   'South_Lanarkshire', 'Stirling', 'Aberdeen', 'Aberdeenshire',
                                                   'Argyll_and_Bute', 'Edinburgh', 'Renfrewshire',
                                                   'West_Dunbartonshire', 'West_Lothian', 'Angus', 'Dundee',
                                                   'North_Lanarkshire', 'East_Dunbartonshire', 'Glasgow']),

                     'Poland': ['All'] + sorted(['Świętokrzyskie', 'Wielkopolskie', 'Kujawsko-Pomorskie',
                                                 'Lubelskie', 'Małopolskie', 'Dolnośląskie', 'Lubuskie',
                                                 'Mazowieckie', 'Opolskie', 'Podlaskie', 'Pomorskie',
                                                 'Podkarpackie', 'Zachodniopomorskie', 'Łódzkie', 'Śląskie',
                                                 'Warmińsko-Mazurskie']),

                     'Switzerland': ['All'] + sorted(['Zurich', 'Bern', 'Luzern', 'Uri', 'Schwyz', 'Obwalden',
                                                      'Nidwalden', 'Glarus', 'Zug', 'Fribourg', 'Solothurn',
                                                      'Basel-Stadt', 'Basel-Landschaft', 'Schaffhausen',
                                                      'Appenzell_Ausserrhoden', 'Appenzell_Innerrhoden', 'St._Gallen',
                                                      'Graubünden', 'Aargau', 'Thurgau', 'Ticino', 'Vaud', 'Valais',
                                                      'Neuchâtel', 'Genev', 'Jura']),

                     'Morocco': ['All'] + sorted(['Laayoune', 'Rabat', 'Beni Mellal', 'Dakhla', 'Tanger',
                                                  'Marrakech', 'Daraa', 'Guelmim', 'Fes', 'Oriental', 'Casablanca',
                                                  'Souss_Massa']),

                     'Tunisia': ['All'] + sorted(['Ariana', 'Béja', 'Ben_Arous', 'Bizerte', 'Gabès', 'Gafsa',
                                                  'Jendouba', 'Kairouan', 'Kasserine', 'Kebili', 'Kef', 'Mahdia',
                                                  'Manouba', 'Medenine', 'Monastir', 'Nabeul', 'Sfax', 'Sidi_Bouzid',
                                                  'Siliana', 'Sousse', 'Tataouine', 'Tozeur', 'Tunis', 'Zaghouan']),

                     'Finland': ['All'] + sorted(['Southern_Savonia', 'Lapland', 'Kainuu', 'Northern_Ostrobothnia',
                                                  'Eastern_Uusimaa', 'Kymenlaakso', 'Päijänne_Tavastia',
                                                  'South_Karelia', 'Uusimaa', 'Tavastia_Proper', 'North_Karelia',
                                                  'North_Savonia', 'Central_Finland', 'Central_Ostrobothnia',
                                                  'Finland_Proper', 'Ostrobothnia', 'Pirkanmaa', 'Satakunta',
                                                  'Southern_Ostrobothnia']),

                     'Turkey': ['All'] + sorted(['Adana', 'Adiyaman', 'Afyon', 'Agri', 'Aksaray', 'Amasya',
                                                 'Ankara', 'Antalya', 'Ardahan', 'Artvin', 'Aydin', 'Balikesir',
                                                 'Bartin', 'Batman', 'Bayburt', 'Bilecik', 'Bingol', 'Bitlis',
                                                 'Bolu', 'Burdur', 'Bursa', 'Canakkale', 'Cankiri', 'Corum',
                                                 'Denizli', 'Diyarbakir', 'Duzce', 'Edirne', 'Elazig', 'Erzincan',
                                                 'Erzurum', 'Eskisehir', 'Gaziantep', 'Giresun', 'Gumushane',
                                                 'Hakkari', 'Hatay', 'Igdir', 'Isparta', 'Istanbul', 'Izmir',
                                                 'Kahramanmaras', 'Karabuk', 'Karaman', 'Kars', 'Kastamonu',
                                                 'Kayseri', 'Kilis', 'Kirikkale', 'Kirklareli', 'Kirsehir',
                                                 'Kocaeli', 'Konya', 'Kutahya', 'Malatya', 'Manisa', 'Mardin',
                                                 'Mersin', 'Mugla', 'Mus', 'Nevsehir', 'Nigde', 'Ordu', 'Osmaniye',
                                                 'Rize', 'Sakarya', 'Samsun', 'Sanliurfa', 'Siirt', 'Sinop',
                                                 'Sirnak', 'Sivas', 'Tekirdag', 'Tokat', 'Trabzon', 'Tunceli',
                                                 'Usak', 'Van', 'Yalova', 'Yozgat', 'Zonguldak']),

                     'Austria': ['All'] + sorted(['Vien', 'Karnten', 'Burgenland', 'Niederosterreich', 'Steiermark',
                                                  'Oberosterreich', 'Salzburg', 'Tirol', 'Vorarlberg']),

                     'Belgium': ['All'] + sorted(['Brussels', 'Antwerp', 'Limburg', 'East Flanders',
                                                  'Flemish_Brabant', 'West_Flanders', 'Wallon', 'Hainaut', 'Liège',
                                                  'Luxembourg', 'Namur']),

                     'Liechtenstein': ['All'] + sorted([]),

                     'Iceland': ['All'] + sorted([]),

                     'Norway': ['All'] + sorted(['Agder', 'Finnmark', 'Innlandet', 'Møre_og_Romsdal', 'Nordland',
                                                 'Oslo', 'Rogaland', 'Trøndelag', 'Vestfold_Og_Telemark',
                                                 'Vestland', 'Viken']),

                     'Estonia': ['All'] + sorted([]),

                     'Hungary': ['All'] + sorted(['Bács-Kiskun', 'Baranya', 'Békés', 'Borsod-Abaúj-Zemplén',
                                                  'Budapest', 'Csongrád', 'Fejér', 'Győr-Moson-Sopron',
                                                  'Hajdú-Bihar', 'Heves', 'Jász-Nagykun-Szolnok',
                                                  'Komárom-Esztergom', 'Nógrád', 'Pest', 'Somogy',
                                                  'Szabolcs-Szatmár-Bereg', 'Tolna', 'Vas', 'Veszprém', 'Zala']),

                     'Czech': ['All'] + sorted(['Ústí_nad_Labem', 'South_Bohemian', 'South_Moravia',
                                                'Karlovy_Vary', 'Hradec_Králové', 'Hochland', 'Liberec',
                                                'Moravia-Silesia', 'Olomouc', 'Pardubice', 'Pilsen', 'Prague',
                                                'Central_Bohemian', 'Zlín']),

                     'Slovakia': ['All'] + sorted(['Bratislava', 'Trnava', 'Trenčín', 'Nitra', 'Zilina',
                                                   'Banská_Bystrica', 'Prešov', 'Kosice']),

                     'Romania': ['All'] + sorted(['Botosani', 'Satu_Mare', 'Maramures', 'Suceava', 'Bihor', 'Iasi',
                                                  'Bistrita-Nasaud', 'Salaj', 'Cluj', 'Neamt', 'Mures', 'Harghita',
                                                  'Vaslui', 'Bacau', 'Arad', 'Alba', 'Hunedoara', 'Covasna', 'Sibiu',
                                                  'Timis', 'Vrancea', 'Galati', 'Brasov', 'Buzau', 'Caras-Severin',
                                                  'Arges', 'Valcea', 'Braila', 'Prahova', 'Dambovita', 'Gorj',
                                                  'Mehedinti', 'Olt', 'Ialomita', 'Constanta', 'Ilfov', 'Dolj',
                                                  'Calarasi', 'Giurgiu', 'Teleorman', 'Tulcea', 'Bucharest']),

                     'Bosnia': ['All'] + sorted([]),

                     'Indonesia': ['All'] + sorted(['Irian', 'Nusa_Tenggara', 'Gorontalo', 'Sulawesi', 'Yogyakarta',
                                                    'Java', 'Probanten', 'Maluku', 'Kalimantan', 'Jakarta', 'Bali',
                                                    'Riau', 'Sumatera', 'Bangka', 'Jambi', 'Lampung', 'Bengkulu',
                                                    'Aceh']),

                     'Australia': ['All'] + sorted(['Northern_Territory', 'Australian_Capital_Territory', 'Tasmania',
                                                    'South_Australia', 'Victoria', 'Western_Australia', 'Queensland',
                                                    'New_South_Wales']),

                     'Russia': ['All'] + sorted(['Buryatia', 'Karachay-Cherkess', 'Sakhalin', 'Voronezh', 'Tomsk',
                                                 'Novosibirsk', 'Nenets_Okrug', 'Magadan', 'Kamchatka', 'Primorsky',
                                                 'Stavropol', 'Altai', 'Moscow', 'Tuva', 'Tambov', 'Sverdlovsk',
                                                 'Khanty–Mansi_Okrug_–_Yugra', 'Chukotka_Okrug', 'Tyumen',
                                                 'Vladimir', 'Volgograd', 'Orenburg', 'Samara', 'Astrakhan',
                                                 'Adygea', 'Kalmykia', 'Krasnodar', 'Rostov', 'Murmansk', 'Pskov',
                                                 'St_Petersburg', 'Leningrad', 'Mordovia', 'Tatarstan', 'Kirov',
                                                 'Kostroma', 'Tver', 'Tula', 'Kaluga', 'Ulyanovsk', 'Mari_El',
                                                 'Smolensk', 'Perm', 'Ivanovo', 'Chuvash', 'North_Ossetia-Alania',
                                                 'Bryansk', 'Penza', 'Belgorod', 'Lipetsk', 'Novgorod',
                                                 'Arkhangelsk', 'Nizhny Novgorod', 'Kurgan', 'Kursk', 'Zabaykalsky',
                                                 'Ryazan', 'Yamalo-Nenets Okrug', 'Krasnoyarsk', 'Sakha',
                                                 'Dagestan', 'Omsk', 'Komi', 'Chechen', 'Kabardino-Balkar',
                                                 'Saratov', 'Kaliningrad', 'Oryol', 'Karelia', 'Irkutsk', 'Amur',
                                                 'Jewish', 'Khabarovsk', 'Kemerovo', 'Khakassia', 'Yaroslavl',
                                                 'Udmurt', 'Vologda', 'Ingushetia', 'Chelyabinsk', 'Bashkortostan']),

                     'Ukraine': ['All'] + sorted(['Cherkasy', 'Chernihiv', 'Chernivtsi', 'Dnipropetrovsk', 'Donetsk',
                                                  'Ivano-Frankivsk', 'Kharkiv', 'Kherson', 'Khmelnytskyi', 'Kiev',
                                                  'Kirovohrad', 'Luhansk', 'Lviv', 'Mykolaiv', 'Odessa', 'Poltava',
                                                  'Rivne', 'Sumy', 'Ternopil', 'Vinnytsia', 'Volyn', 'Zakarpattia',
                                                  'Zaporizhia', 'Zhytomyr']),

                     'Croatia': ['All'] + sorted(['Bjelovarska', 'Brod-Posavina', 'Dubrovnik-Neretva', 'Istria',
                                                  'Karlovac', 'Koprivnica-Križevci', 'Krapina-Zagorje', 'Lika-Senj',
                                                  'Međimurje', 'Osijek-Baranja', 'Požega-Slavonia',
                                                  'Primorje-Gorski', 'Sibenik-Knin', 'Sisak-Moslavina',
                                                  'Split-Dalmatia', 'Varaždin', 'Virovitica-Podravina',
                                                  'Vukovar-Srijem', 'Zadar', 'Zagreb']),

                     'Israel': ['All'] + sorted([]),

                     'Lebanon': ['All'] + sorted(['Akkar', 'Baalbek', 'Beirut', 'Bekaa', 'Mount Lebanon',
                                                  'Nabatiyeh', 'North_Governorate', 'South_Governorate']),

                     'Argentina': ['All'] + sorted(['Buenos_Aires', 'Catamarca', 'Chaco', 'Chubut', 'Corrientes',
                                                    'Córdoba', 'Entre_Ríos', 'Formosa', 'Jujuy', 'La_Pampa',
                                                    'La_Rioja', 'Mendoza', 'Misiones', 'Neuquén', 'Río_Negro', 'Salta',
                                                    'San_Juan', 'San_Luis', 'Santa_Cruz', 'Santa_Fe',
                                                    'Santiago_del_Estero', 'Tierra_del_Fuego', 'Tucumán']),

                     'Philippines': ['All'] + sorted(['Muslim_Mindanao', 'Bicol', 'Calabarzon', 'Cagayan_Valley',
                                                      'Caraga', 'Central_Luzon', 'Central_Visayas', 'Cordillera',
                                                      'Davao', 'Eastern_Visayas', 'Ilocos', 'Mimaropa',
                                                      'National_Capital_Region', 'Northern_Mindanao', 'Soccsksargen',
                                                      'Western_Visayas', 'Zamboanga']),

                     'Korea': ['All'] + sorted(['Busan', 'Chungcheongbuk', 'Chungcheongnam', 'Daegu', 'Daejeon',
                                                'Gangwon', 'Gwangju', 'Gyeonggi', 'Gyeongsangbuk', 'Gyeongsangnam',
                                                'Incheon', 'Jeju', 'Jeollabuk', 'Jeollanam', 'Seoul', 'Ulsan']),

                     'New_Zealand': ['All'] + sorted(['Auckland', 'Bay_of_Plenty', 'Canterbury', 'Gisborne',
                                                      "Hawke's_Bay", 'Manawatu-Wanganui', 'Marlborough', 'Nelson',
                                                      'Northland', 'Otago', 'Southland', 'Taranaki', 'Waikato',
                                                      'Wellington', 'West_Coast']),

                     'Thailand': ['All'] + sorted(['Amnat_Charoen', 'Ang_Thong', 'Bangkok', 'Bueng_Kan', 'Buri_Ram',
                                                   'Chachoengsao', 'Chai_Nat', 'Chaiyaphum', 'Chanthaburi',
                                                   'Chiang_Mai', 'Chiang_Rai', 'Chon_Buri', 'Chumphon', 'Kalasin',
                                                   'Kamphaeng_Phet', 'Kanchanaburi', 'Khon_Kaen', 'Krabi', 'Lampang',
                                                   'Lamphun', 'Loei', 'Lop_Buri', 'Mae_Hong_Son', 'Maha_Sarakham',
                                                   'Mukdahan', 'Nakhon_Nayok', 'Nakhon_Pathom', 'Nakhon_Phanom',
                                                   'Nakhon_Ratchasima', 'Nakhon_Sawan', 'Nakhon_Si_Thammarat',
                                                   'Narathiwat', 'Nong_Bua_Lam_Phu', 'Nong_Khai', 'Nonthaburi',
                                                   'Pathum_Thani', 'Pattani', 'Phangnga', 'Phatthalung', 'Phayao',
                                                   'Phetchabun', 'Phetchaburi', 'Phichit', 'Phitsanulok',
                                                   'Phra_Nakhon_Si_Ayutthaya', 'Phrae', 'Phuket', 'Prachin_Buri',
                                                   'Prachuap_Khiri_Khan', 'Ranong', 'Ratchaburi', 'Rayong', 'Roi_Et',
                                                   'Sa_Kaeo', 'Sakon_Nakhon', 'Samut_Prakan', 'Samut_Sakhon',
                                                   'Samut_Songkhram', 'Saraburi', 'Satun', 'Si_Sa_Ket', 'Sing_Buri',
                                                   'Songkhla', 'Sukhothai', 'Suphan_Buri', 'Surat_Thani', 'Surin',
                                                   'Tak', 'Trang', 'Trat', 'Ubon_Ratchathani', 'Udon_Thani',
                                                   'Uthai_Thani', 'Uttaradit', 'Yala', 'Yasothon']),

                     'Japan': ['All'] + sorted(['Hokkaido', 'Aomori', 'Akita', 'Iwate', 'Yamagata', 'Miyagi',
                                                'Niigata', 'Fukushima', 'Ishikawa', 'Tochigi', 'Gunma', 'Nagano',
                                                'Toyama', 'Ibaraki', 'Gifu', 'Fukui', 'Saitama', 'Chiba',
                                                'Yamanashi', 'Tokyo', 'Shiga', 'Kanagawa', 'Shizuoka', 'Aichi',
                                                'Mie', 'Osaka', 'Nara', 'Wakayama', 'Kyoto', 'Hyogo', 'Tottori',
                                                'Shimane', 'Okayama', 'Hiroshima', 'Yamaguchi', 'Kagawa',
                                                'Tokushima', 'Ehime', 'Fukuoka', 'Kochi', 'Oita', 'Saga',
                                                'Nagasaki', 'Kumamoto', 'Kagoshima', 'Okinawa', 'Miyazaki']),

                     'Vietnam': ['All'] + sorted(
                         ['An_Giang', 'Vung_Tau', 'Bac_Giang', 'Bac_Kan', 'Bac_Lieu', 'Bac_Ninh', 'Ben_Tre',
                          'Binh_Dinh', 'Binh_Duong', 'Binh_Phuoc', 'Binh_Thuan', 'Ca_Mau', 'Can_Tho', 'Cao_Bang',
                          'Da_Nang', 'Dak_Lak', 'Dak_Nong', 'Dien_Bien', 'Dong_Nai', 'Dong_Thap', 'Gia_Lai', 'Ha_Giang',
                          'Ha_Nam', 'Hanoi', 'Ha_Tinh', 'Hai_Duong', 'Hai_Phong', 'Hau_Giang', 'Hoa_Binh', 'Hung_Yen',
                          'Khanh_Hoa', 'Kien_Giang', 'Kon_Tum', 'Lai_Chau', 'Lam_Dong', 'Lang_Son', 'Lao_Cai',
                          'Long_An', 'Nam_Dinh', 'Nghe_An', 'Ninh_Binh', 'Ninh_Thuan', 'Phu_Tho', 'Phu_Yen',
                          'Quang_Binh', 'Quang_Nam', 'Quang_Ngai', 'Quang_Ninh', 'Quang_Tri', 'Soc_Trang', 'Son_La',
                          'Tay_Ninh', 'Thai_Binh', 'Thai_Nguyen', 'Thanh_Hoa', 'Thua_Thien_Hue', 'Tien_Giang',
                          'Ho_Chi_Minh', 'Tra_Vinh', 'Tuyen_Quang', 'Vinh_Long', 'Vinh_Phuc', 'Yen_Bai']),

                     'China': ['All'] + sorted(['Heilongjian', 'Xinjiang', 'Shanxi', 'Tibet', 'Shandong', 'Henan',
                                                'Jiangsu', 'Anhui', 'Hubei', 'Zhejiang', 'Jiangxi', 'Hunan',
                                                'Yunnan', 'Guizhou', 'Fujian', 'Guangxi', 'Guangdong', 'Hainan',
                                                'Jilin', 'Liaoning', 'Qinghai', 'Gansu', 'Shaanxi',
                                                'Inner_Mongolia', 'Chongqing', 'Hebei', 'Sichuan', 'Macau',
                                                'Ningxia', 'Tianjin', 'Shanghai', 'Beijing', 'Hong_Kong']),

                     'India': ['All'] + sorted(['Delhi', 'Jharkhand', 'Karnataka', 'Kerala', 'Maharashtra',
                                                'Manipur', 'Daman_and_Diu', 'Meghalaya', 'Mizoram', 'Odisha',
                                                'Gujarat', 'Haryana', 'Himachal_Pradesh', 'Rajasthan', 'Sikkim',
                                                'Tamil_Nadu', 'Telangana', 'Tripura', 'Uttarakhand',
                                                'Uttar_Pradesh', 'West_Bengal', 'Chandigarh', 'Chhattisgarh',
                                                'Madhya_Pradesh', 'Goa', 'Jammu_and_Kashmir', 'Nagaland',
                                                'Pondicherry', 'Punjab', 'Dadra_and_Nagar_Haveli',
                                                'Andaman_and_Nicobar_Islands', 'Andhra_Pradesh', 'Assam', 'Bihar',
                                                'Lakshadweep']),

                     'South_Africa': ['All'] + sorted(['Eastern_Cape', 'Free_State', 'Gauteng', 'KwaZulu-Natal',
                                                       'Limpopo', 'Mpumalanga', 'North_West', 'Northern_Cape',
                                                       'Western_Cape']),

                     'Egypt': ['All'] + sorted(['Daqahliyah', 'Red_Sea', 'Behera', 'Faiyum', 'Gharbiya',
                                                'Alexandria', 'Ismailiyah', 'Giza', 'Minufiyah', 'Minya', 'Cairo',
                                                'Kalioubiya', 'Luxor', 'Southern_Desert', 'Suweiz', 'Sharkia',
                                                'Assouan', 'Asyout', 'Bani_Suwayf', 'Port_Said', 'Dumiāt',
                                                'South_Sinai', 'Sheikh', 'Western_Desert', 'Kena', 'North_Sinai',
                                                'Girgeh']),

                 }
                 }
